### ISSUE TITLE
TypeError when connecting wallet (Brave browser)

### ISSUE THREAD

**Issue by thorstenhirsch** [zama-ai/fhevm-remix-plugin#4]
After adding the plugin in Remix I click on "Connect Wallet" in the fhEVM plugin menu. Nothing happens, except the following error in the js console:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'request')
    at o (index-DlpNvwU2.js:60:295182)
    at Object.AU (index-DlpNvwU2.js:37:9855)
    at gU (index-DlpNvwU2.js:37:10009)
    at CU (index-DlpNvwU2.js:37:10066)
    at uc (index-DlpNvwU2.js:37:31446)
    at kn (index-DlpNvwU2.js:37:31863)
    at index-DlpNvwU2.js:37:36776
    at ok (index-DlpNvwU2.js:40:36935)
    at Wr (index-DlpNvwU2.js:37:8991)
    at ws (index-DlpNvwU2.js:37:33150)
```
Unlocking my browser's wallet before clicking on "Connect Wallet" makes no difference.

**Comment by poppyseedDev** [comment]
We were debugging this problem internally as well. It seems like this is more of a remix + multiple wallet issue, than a Remix-Zama plugin problem.

See: https://ethereum.stackexchange.com/questions/147362/why-injected-provider-metamask-not-working

The problem for me occurred already while having multiple wallets installed (in my case Metamask + Phantom wallet). It looks like the problem occurs already already when connecting the wallet with the `Injected provider - Metamask` (under `Deploy and run transactions`).

If you only keep Metamask as a wallet and delete other wallet extensions and refresh the Remix cookies, the problem seem to be resolved.
